name: Publish to RedGuides

on:
  workflow_run:
    workflows: ["Publish to Github and Create Release"]
    types:
      - completed

jobs:
  publish:
    if: github.repository == 'DerpleMQ2/rgmercs' && github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Read version
        id: version
        run: |
          VERSION=$(sed -n 's/.*version *= *\([0-9]\+\).*/\1/p' extras/version.lua)
          [ -z "$VERSION" ] && exit 1
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Build zip file
        run: git archive --format=zip --prefix="${{ github.event.repository.name }}/" -o "${{ github.event.repository.name }}_${{ steps.version.outputs.version }}.zip" HEAD

      - name: Generate RedGuides release notes
        shell: bash
        run: |
          VERSION="${{ steps.version.outputs.version }}"
          PREV=$(git describe --tags --abbrev=0 HEAD^ 2>/dev/null || echo "")
          git log --no-merges --pretty=format:"- [%s](${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/commit/%H)%n%b%n~%an" ${PREV:+$PREV..}HEAD > rg_release_notes.md
          cat rg_release_notes.md

      - name: Publish to RedGuides
        uses: RedGuides/redguides-publish@v1
        env:
          REDGUIDES_API_KEY: ${{ secrets.REDGUIDES_API_KEY }}
        with:
          resource_id: "3040"
          version: "${{ steps.version.outputs.version }}"
          file: "${{ github.event.repository.name }}_${{ steps.version.outputs.version }}.zip"
          message: "rg_release_notes.md"
          domain: "https://raw.githubusercontent.com/${{ github.repository }}/${{ github.event.repository.default_branch }}/"